# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger:
  - main

jobs:
  - job: 'gradlew_build'

    pool:
        vmImage: 'windows-latest'

    steps:
      - task: Gradle@2
        displayName: build and test dev ai-android service
        inputs:
          workingDirectory: '$(system.defaultWorkingDirectory)/AccessibilityInsightsForAndroidService'
          gradleWrapperFile: 'AccessibilityInsightsForAndroidService/gradlew'
          gradleOptions: '-Xmx3072m'
          options: -S
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'

      - task: ComponentGovernanceComponentDetection@0
        displayName: 'dependency detection (Component Governance)'
        timeoutInMinutes: 5

      - task: msospo.ospo-extension.8d7f9abb-6896-461d-9e25-4f74ed65ddb2.notice@0
        displayName: 'generate NOTICE.html file'
        inputs:
            outputformat: html
        timeoutInMinutes: 5